CREATE DATABASE IF NOT EXISTS cop2026;
USE cop2026;

CREATE TABLE users (
id INT AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(50) UNIQUE NOT NULL,
password VARCHAR(255) NOT NULL,
country VARCHAR(50),
favorite_team VARCHAR(50),
points INT DEFAULT 0,
balance INT DEFAULT 1000,
role VARCHAR(20) DEFAULT 'user',
banned BOOLEAN DEFAULT FALSE,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE news (
id INT AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(255),
content TEXT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE matches (
id INT AUTO_INCREMENT PRIMARY KEY,
team1 VARCHAR(100),
team2 VARCHAR(100),
match_date DATETIME,
score1 INT DEFAULT NULL,
score2 INT DEFAULT NULL,
status VARCHAR(20) DEFAULT 'open'
);

CREATE TABLE predictions (
id INT AUTO_INCREMENT PRIMARY KEY,
user_id INT,
match_id INT,
prediction_team1 INT,
prediction_team2 INT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE wallet_transactions (
id INT AUTO_INCREMENT PRIMARY KEY,
sender_id INT,
receiver_id INT,
amount INT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
